apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: notifications-backend-config
  namespace: essa-project
spec:
  healthCheck:
    type: HTTP
    port: 6970
    requestPath: /q/health/ready